config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "app#landing"

  get 'play', to: 'app#play'
  get 'game', to: 'app#game'
  get 'login', to: 'app#login'
  get 'signup', to: 'app#signup'
  get 'profiles/me', to: 'profiles#show'

  namespace :players do
    root to: redirect('/profiles/me')
  end

  devise_for :player, path: 'api/v1/auth', controllers: {
    sessions: 'api/sessions',
    registrations: 'api/registrations'
  }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do    
      resources :games, only: [:create, :show, :index] do
        member do
          put 'reveal', to: 'player_actions#reveal'
          put 'flag', to: 'player_actions#flag'
          put 'unflag', to: 'player_actions#unflag'
        end
      end
    end
  end
  
end

app/views/app/game.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-4 p-1 window">

    <div class="title-bar">
      <div class="title-bar-text">Minesweeper - The greatest game!</div>
      <div class="title-bar-controls">
        <button aria-label="Minimize"></button>
        <button aria-label="Maximize"></button>
        <button aria-label="Close"></button>
      </div>
    </div>

    <div class="window-body to-content p-4">
      <h3 class="my-0">Game</h3>
      <hr>

      <div class="mb-5 d-flex">
        <div class="flex-fill">
          <button id="new-game">Start new game</button>
        </div>

        <button>
          <%= link_to 'Back', root_path %>
        </button>
      </div>

      <fieldset class="py-2">
        <div class="field-row">Game mode:</div>
        <div class="field-row">
          <input id="beginner" type="radio" name="level" value="beginner">
          <label for="beginner">Beginner (8x8)</label>
        </div>
        <div class="field-row">
          <input id="intermediate" type="radio" name="level" value="intermediate" checked>
          <label for="intermediate">Intermediate (16x16)</label>
        </div>
        <div class="field-row">
          <input id="expert" type="radio" name="level" value="expert">
          <label for="expert">Expert (24x24)</label>
        </div>
        <div class="field-row">
          <input id="custom" type="radio" name="level" value="custom">
          <label for="custom">Custom (min: 2, max: 30)</label>
        </div>
        <div class="field-row pl-3">
          <label for="custom-rows" style="min-width: 50px">rows</label>
          <input id="custom-rows" name="rows" type="number" disabled/>
        </div>
        <div class="field-row pl-3">
          <label for="custom-cols" style="min-width: 50px">columns</label>
          <input id="custom-cols" name="columns" type="number" disabled/>
        </div>
        <div class="field-row pl-3">
          <label for="custom-mines" style="min-width: 50px">mines</label>
          <input id="custom-mines" name="mines" type="number" disabled/>
          <span>min: 1 / max: (rows * columns) - 1 </span>
        </div>
      </fieldset>

      <div id="message" class="py-2 text-danger"></div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "game" %>

app/views/app/landing.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-5 p-1 window">
    <div class="title-bar">
      <div class="title-bar-text">Minesweeper - The greatest game!</div>
      <div class="title-bar-controls">
        <button aria-label="Minimize"></button>
        <button aria-label="Maximize"></button>
        <button aria-label="Close"></button>
      </div>
    </div>

    <div class="window-body p-4">
      <h3 class="my-0">Welcome to Minesweeper!</h3>
      <hr>
      <div>
        <div class="mb-5 d-flex">
          <div class="flex-fill">
            <button>
              <%= link_to 'Play Now', game_path %>
            </button>
          </div>

          <button>
            <%= link_to 'Login', login_path %>
          </button>

          <button>
            <%= link_to "Sign up", signup_path %><br />
          </button>
        </div>
      </div>

      <p>A single-player puzzle video game</p>

      <p>
        The objective of the game is to clear a rectangular board containing hidden 
        "mines" or bombs without detonating any of them, with help from clues about 
        the number of neighboring mines in each field. The game originates from the 
        1960s, and has been written for many computing platforms in use today. 
        It has many variations and offshoots.
      </p>

      <h5>Quick Start:</h5>

      <ul>
        <li>You are presented with a board of squares.</li>
        <li>Some squares contain mines (bombs), others don't.</li>
        <li>If you click on a square containing a bomb, you lose.</li>
        <li>If you manage to click all the squares (without clicking on any bombs) you win.</li>
        <li>
          Clicking a square which doesn't have a bomb reveals the number of neighbouring squares containing bombs.
          Use this information plus some guess work to avoid the bombs.
        </li>
        <li>To open a square, point at the square and click on it.</li> 
        <li>To mark a square you think is a bomb, point and right-click.</li>
      </ul>      
    </div>
  </div>
</div>

<%= javascript_pack_tag "landing" %>

app/views/app/login.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-5 p-1 window">
    <div class="title-bar">
      <div class="title-bar-text">Minesweeper - The greatest game!</div>
      <div class="title-bar-controls">
        <button aria-label="Minimize"></button>
        <button aria-label="Maximize"></button>
        <button aria-label="Close"></button>
      </div>
    </div>

    <div class="window-body to-content p-4">
      <h3 class="my-0">Log in</h3>
      <hr>

      <div class="d-flex flex-column pt-4">
        <div class="field mb-4">
          <label for="nickname">Nickname</label>
          <input id="nickname" name="nickname" type="text" autofocus/>
        </div>

        <div class="field mb-4">
          <label for="password">Password</label>
          <input id="password" name="password" type="password"/>
        </div>

        <div class="actions">
          <button id="login" class="mr-4">Login</button>
          
          <%= link_to "Sign up", signup_path %>
        </div>
      </div>

      <div id="message" class="pt-4 text-danger"></div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "login" %>

app/views/app/play.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-7 p-1 window">

    <div class="title-bar">
      <div class="title-bar-text">Minesweeper - The greatest game!</div>
      <div class="title-bar-controls">
        <button aria-label="Minimize"></button>
        <button aria-label="Maximize"></button>
        <button aria-label="Close"></button>
      </div>
    </div>

    <div class="window-body p-4">
      <h3 class="my-0">Play</h3>
      <hr>

      <div class="d-flex mb-2">
        <div class="flex-fill">
          <button id="new-game">
            <%= link_to 'New game', game_path %>
          </button>
        </div>

        <button>
          <%= link_to 'Back', profiles_me_path %>
        </button>
      </div>

      <div class="mb-4">
        <div><b>Controllers</b></div>
        <div>Left click: reveal cell</div>
        <div>Right click: flag/unflag cell</div>
      </div>

      <div class="counters px-5 d-flex justify-content-between">
        <h4 id="mines-count" class="m-0"></h4>
        <h4 id="flags-count" class="m-0"></h4>
        <h4 id="time-count"  class="m-0"></h4>
      </div>

      <div class="d-flex flex-column align-items-center pt-4">
        <div id="board"></div>
      </div>

      <div class="">
        <div><b>Instructions</b></div>
        <ul>
          <li>Some squares contain mines (bombs), others don't.</li>
          <li>If you click on a square containing a bomb, you lose.</li>
          <li>If you manage to click all the squares (without clicking on any bombs) you win.</li>
          <li>
            Clicking a square which doesn't have a bomb reveals the number of neighbouring squares containing bombs.
            Use this information plus some guess work to avoid the bombs.
          </li>
        </ul>      
      </div>

    </div>
  </div>

  <div class="window p-1" id="window-result">
    <div class="title-bar">
      <div class="title-bar-text">Minesweeper - The greatest game!</div>
    </div>

    <div class="p-3">
      <div id="result" class="text-center"></div>    
    </div>
  </div>
</div>

<%= javascript_pack_tag "play" %>

app/views/app/signup.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-5 p-1 window">
    <div class="title-bar">
      <div class="title-bar-text">Minesweeper - The greatest game!</div>
      <div class="title-bar-controls">
        <button aria-label="Minimize"></button>
        <button aria-label="Maximize"></button>
        <button aria-label="Close"></button>
      </div>
    </div>

    <div class="window-body to-content p-4">
      <h3 class="my-0">Sign Up</h3>
      <hr>

      <div class="d-flex flex-column pt-4">
        <div class="field mb-4">
          <label for="email" class="d-block">Email</label>
          <input id="email" name="email" type="email" autofocus/>
        </div>

        <div class="field mb-4">
          <label for="nickname" class="d-block">Nickname</label>
          <input id="nickname" name="nickname" type="text"/>
        </div>

        <div class="field mb-4">
          <label for="password" class="d-block">Password</label>
          <input id="password" name="password" type="password"/>
        </div>

        <div class="actions">
          <button id="signup" class="mr-4">Sign Up</button>
          
          <%= link_to "Home", root_path %>
        </div>
      </div>

      <div id="message" class="pt-4 text-danger"></div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "signup" %>